apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources
  labels:
     grafana_datasource: "1"
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
stringData:
  datasource.yaml: |-
    # config file version
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-operated:9090
        isDefault: true
        version: 1
        editable: true
        jsonData:
          tlsSkipVerify: true
          timeInterval: "5s"