apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    fabric8.io/generated-by: exposecontroller
    kubernetes.io/tls-acme: "true"
  labels:
    provider: fabric8
  name: grafana
  namespace: jx
spec:
  rules:
  - host: "{{ .Values.config.service }}.{{ .Values.config.domain }}"
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 80
  tls:
  - hosts:
    - "{{ .Values.config.service }}.{{ .Values.config.domain }}"
    secretName: "tls-{{ .Values.config.domain | replace "." "-" }}-p"
