apiVersion: skaffold/v1beta11
kind: Config

profiles:
  - name: grafana-config
    deploy:
      helm:
        releases:
        - name: grafana-test
          chartPath: grafana-config
          valuesFiles:
            - grafana-config/values.yaml
          # =====================================
          values:
          # =====================================
          setValues:
            grafana.ingress.enabled: true

  - name: prometheus
    deploy:
      helm:
        releases:
          - name: prometheus-test
            chartPath: prometheus
            valuesFiles:
              - prometheus/values-jx.yaml
            # =====================================
            values:
            # =====================================
            setValues:
              prometheus-operator.prometheus.ingress.enabled: true
              prometheus-operator.alertmanager.ingress.enabled: false

  - name: aws-alb-ingress-controller
    deploy:
      helm:
        releases:
          - name: aws-alb-ingress-controller
            chartPath: aws-alb-ingress-controller
            valuesFiles:
              - aws-alb-ingress-controller/values.yaml
            # =====================================
            values:
            # =====================================
            setValues:

  - name: oauth-secret
    deploy:
      helm:
        releases:
          - name: oauth-secret
            chartPath: oauth-secret
            valuesFiles:
              - oauth-secret/values.yaml
            # =====================================
            values:
            # =====================================
            setValues:


  - name: doordawn-grafana-config
    deploy:
      helm:
        releases:
          - name: grafana
            chartPath: charts/grafana-config
            valuesFiles:
              - charts/grafana-config/values-doordawn.yaml
            # =====================================
            values:
            # =====================================
            setValues:
              grafana.ingress.enabled: true

  - name: prod-grafana-config
    deploy:
      helm:
        releases:
        - name: grafana
          chartPath: charts/grafana-config
          valuesFiles:
            - charts/grafana-config/values.yaml
          # =====================================
          values:
          # =====================================
          setValues:
            grafana.ingress.enabled: false


  - name: doordawn-prometheus
    deploy:
      helm:
        releases:
        - name: prometheus
          chartPath: charts/prometheus
          valuesFiles:
            - charts/prometheus/values-doordawn.yaml
          # =====================================
          values:
          # =====================================
          setValues:
            prometheus-operator.prometheus.ingress.enabled: false
            prometheus-operator.alertmanager.ingress.enabled: false

  - name: prod-prometheus
    deploy:
      helm:
        releases:
        - name: prometheus
          chartPath: charts/prometheus
          valuesFiles:
            - charts/prometheus/values-prod.yaml
          # =====================================
          values:
          # =====================================
          setValues:
            prometheus-operator.prometheus.ingress.enabled: false
            prometheus-operator.alertmanager.ingress.enabled: false

  - name: cloudwatch-exporter
    deploy:
      helm:
        releases:
        - name: cloudwatch-exporter
          chartPath: charts/cloudwatch-exporter
          valuesFiles:
            - charts/cloudwatch-exporter/values.yaml
          # =====================================
          values:
          # =====================================
          setValues:

  - name: cluster-monitoring
    deploy:
      helm:
        releases:
        - name: cluster-monitoring
          chartPath: charts/cluster-monitoring
          valuesFiles:
            - charts/cluster-monitoring/values.yaml
          # =====================================
          values:
          # =====================================
          setValues:

  - name: doordawn-cloudwatch-exporter
    deploy:
      helm:
        releases:
        - name: cloudwatch-exporter
          chartPath: charts/cloudwatch-exporter
          valuesFiles:
            - charts/cloudwatch-exporter/values-doordawn.yaml
          # =====================================
          values:
          # =====================================
          setValues:

  - name: doordawn-kube2iam
    deploy:
      helm:
        releases:
        - name: kube2iam
          namespace: default
          chartPath: charts/kube2iam
          valuesFiles:
            - charts/kube2iam/values-doordawn.yaml
          # =====================================
          values:
          # =====================================
          setValues:


  - name: prod-kube2iam
    deploy:
      helm:
        releases:
        - name: kube2iam
          namespace: default
          chartPath: charts/kube2iam
          valuesFiles:
            - charts/kube2iam/values-israel-production.yaml
          # =====================================
          values:
          # =====================================
          setValues:

  - name: thanos-config
    deploy:
      helm:
        releases:
        - name: thanos
          chartPath: charts/thanos-config
          valuesFiles:
            - charts/thanos-config/values.yaml
          # =====================================
          values:
          # =====================================
          setValues:


